name: Build and Publish

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  APP_NAME: vercel-blog
  IMAGE_NAME: ${{ github.repository_owner }}/$APP_NAME

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and push chart
        run: |
          # Strip 'v' prefix from the tag (e.g., v1.0.2 -> 1.0.2)
          VERSION=${GITHUB_REF_NAME#v}
          
          # Package using the dynamic version and set appVersion to match
          helm package helm/ --version "$VERSION" --app-version "$VERSION"
          
          # Push the specific file created
          helm push $APP_NAME-"$VERSION".tgz oci://ghcr.io/${{ github.repository_owner }}/charts